# Generated by Django 5.1 on 2024-08-31 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_brand_ad', models.CharField(max_length=50)),
                ('email_brand_ad', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PostAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ad', models.CharField(max_length=50)),
                ('text_ad', models.TextField(max_length=150)),
                ('site_brand_ad', models.URLField()),
                ('post_ad_one_to_one', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='marketing.brandad')),
            ],
        ),
    ]
