# Generated by Django 5.1 on 2024-09-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_appointment_alter_author_user_one_to_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
